#!/bin/sh

base=$(pwd)
echo "pre-commit hook running from $base"

if [ -d "$base/poc/libs/mirage" ]; then
	echo "Creating mirage patch"
	cd "$base/poc/libs"
	# submodule don't have their own git repo but is stored within the repo (.git/modules)
	# so env variables aren't pointing to the good place
	# env -i executes the provided command in a new environment
	env -i ./generate_patch.sh
	git add mirage.patch
	cd "$base"
fi

if [ -d "$base/doc" ]; then
	echo "Generating latest documentation version"
	cd "$base/doc"
	pandoc -d documentation.yaml -o documentation.pdf
	git add documentation.pdf
	cd "$base"
fi

if [ -d "$base/paper" ]; then
	echo "Generating latest paper version"
	cd "$base/paper"
	pandoc -d paper.yaml -o paper.pdf
	git add paper.pdf
	cd "$base"
fi
