version: "3.8"
services:
  mirage:
    container_name: mirage
    image: mirage
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    ports:
        - "3000:80"
    tty: true
    volumes:
        - .:/poc
        - /dev:/dev