version: "3.8"
services:
  mirage:
    container_name: mirage
    image: mirage
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    ports:
        - "3000:80"
    tty: true
    volumes:
        # mandatory for bbc micro:bit
        - /dev:/dev
        # mirage custom scenarios and modules
        - ./src:/root/.mirage/
        # needed files for poc
        - ./test:/poc/test
        - ./libs:/poc/libs
        - ./server:/poc/server
        - ./public:/poc/public
        - ./shared:/poc/shared
