version: "3.8"
services:
  mirage:
    container_name: mirage-prod
    image: mirage/prod
    privileged: true
    build: .
    network_mode: host
    ports:
        - "3000:80"
    tty: true
    volumes:
        - /dev:/dev